-- Humlehaven backend v1
create table if not exists public.family_members (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (display_name in ('Peter','Ditte','Caroline','Christine')),
  created_at timestamptz not null default now()
);
create table if not exists public.cup_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.family_members(id) on delete cascade,
  day smallint not null check (day between 1 and 24),
  correct boolean not null,
  elapsed_ms integer not null check (elapsed_ms >= 0),
  submitted_at timestamptz not null default now(),
  unique(user_id,day)
);
create table if not exists public.wishes (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.family_members(id) on delete cascade,
  text text not null,
  url text,
  created_at timestamptz not null default now()
);
create table if not exists public.gift_notes (
  id bigint generated by default as identity primary key,
  buyer_id uuid not null references public.family_members(id) on delete cascade,
  recipient_id uuid not null references public.family_members(id) on delete cascade,
  text text not null,
  status text not null default 'idea' check(status in ('idea','bought','wrapped')),
  created_at timestamptz not null default now(),
  check(buyer_id<>recipient_id)
);
alter table public.family_members enable row level security;
alter table public.cup_attempts enable row level security;
alter table public.wishes enable row level security;
alter table public.gift_notes enable row level security;
create policy "family profiles visible to signed in family" on public.family_members for select to authenticated using(true);
create policy "own profile insert" on public.family_members for insert to authenticated with check(auth.uid()=id);
create policy "own profile update" on public.family_members for update to authenticated using(auth.uid()=id) with check(auth.uid()=id);
create policy "attempt status visible to family" on public.cup_attempts for select to authenticated using(true);
create policy "own attempt once" on public.cup_attempts for insert to authenticated with check(auth.uid()=user_id);
create policy "wishes visible to family" on public.wishes for select to authenticated using(true);
create policy "own wishes manage" on public.wishes for all to authenticated using(auth.uid()=owner_id) with check(auth.uid()=owner_id);
create policy "buyer gift notes only" on public.gift_notes for select to authenticated using(auth.uid()=buyer_id);
create policy "buyer gift notes insert" on public.gift_notes for insert to authenticated with check(auth.uid()=buyer_id and auth.uid()<>recipient_id);
create policy "buyer gift notes update" on public.gift_notes for update to authenticated using(auth.uid()=buyer_id) with check(auth.uid()=buyer_id and auth.uid()<>recipient_id);
create policy "buyer gift notes delete" on public.gift_notes for delete to authenticated using(auth.uid()=buyer_id);

-- v2: one authenticated account per family identity
create unique index if not exists family_members_display_name_unique on public.family_members(display_name);

-- v3: Cup privacy is enforced in the database, not only in the UI.
drop policy if exists "attempt status visible to family" on public.cup_attempts;

create or replace function public.get_cup_attempts()
returns table(display_name text, day smallint, correct boolean, elapsed_ms integer)
language sql
security definer
set search_path = public
stable
as $$
  select fm.display_name,
         ca.day,
         case when exists (
           select 1 from public.cup_attempts mine
           where mine.user_id = auth.uid() and mine.day = ca.day
         ) then ca.correct else null end as correct,
         case when exists (
           select 1 from public.cup_attempts mine
           where mine.user_id = auth.uid() and mine.day = ca.day
         ) then ca.elapsed_ms else null end as elapsed_ms
  from public.cup_attempts ca
  join public.family_members fm on fm.id = ca.user_id
  where auth.uid() is not null;
$$;

revoke all on function public.get_cup_attempts() from public;
grant execute on function public.get_cup_attempts() to authenticated;

-- v4: server-authoritative Cup submission.
create table if not exists public.cup_challenges (
  day smallint primary key check(day between 1 and 24),
  correct_answer smallint not null check(correct_answer between 0 and 3)
);
alter table public.cup_challenges enable row level security;
revoke all on public.cup_challenges from anon, authenticated;

insert into public.cup_challenges(day,correct_answer) values
(1,1),(2,1),(3,1),(4,1),(5,1),(6,0),(7,0),(8,0),(9,0),(10,2),(11,0),(12,1),
(13,0),(14,1),(15,1),(16,0),(17,1),(18,0),(19,2),(20,0),(21,1),(22,2),(23,2),(24,1)
on conflict(day) do update set correct_answer=excluded.correct_answer;

drop policy if exists "own attempt once" on public.cup_attempts;

create or replace function public.submit_cup_answer(p_day smallint,p_answer smallint,p_elapsed_ms integer)
returns table(correct boolean,elapsed_ms integer)
language plpgsql
security definer
set search_path=public
as $$
declare v_correct boolean;
begin
  if auth.uid() is null then raise exception 'Not authenticated'; end if;
  if p_day not between 1 and 24 or p_answer not between 0 and 3 then raise exception 'Invalid answer'; end if;
  if p_elapsed_ms < 250 or p_elapsed_ms > 120000 then raise exception 'Invalid elapsed time'; end if;
  if exists(select 1 from public.cup_attempts where user_id=auth.uid() and day=p_day) then raise exception 'Already played'; end if;
  select correct_answer=p_answer into v_correct from public.cup_challenges where day=p_day;
  insert into public.cup_attempts(user_id,day,correct,elapsed_ms) values(auth.uid(),p_day,v_correct,p_elapsed_ms);
  return query select v_correct,p_elapsed_ms;
end;
$$;
revoke all on function public.submit_cup_answer(smallint,smallint,integer) from public;
grant execute on function public.submit_cup_answer(smallint,smallint,integer) to authenticated;
