-- Humlehaven backend v1
create table if not exists public.family_members (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (display_name in ('Peter','Ditte','Caroline','Christine')),
  created_at timestamptz not null default now()
);
create table if not exists public.cup_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.family_members(id) on delete cascade,
  day smallint not null check (day between 1 and 24),
  correct boolean not null,
  elapsed_ms integer not null check (elapsed_ms >= 0),
  submitted_at timestamptz not null default now(),
  unique(user_id,day)
);
create table if not exists public.wishes (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references public.family_members(id) on delete cascade,
  text text not null,
  url text,
  created_at timestamptz not null default now()
);
create table if not exists public.gift_notes (
  id bigint generated by default as identity primary key,
  buyer_id uuid not null references public.family_members(id) on delete cascade,
  recipient_id uuid not null references public.family_members(id) on delete cascade,
  text text not null,
  status text not null default 'idea' check(status in ('idea','bought','wrapped')),
  created_at timestamptz not null default now(),
  check(buyer_id<>recipient_id)
);
alter table public.family_members enable row level security;
alter table public.cup_attempts enable row level security;
alter table public.wishes enable row level security;
alter table public.gift_notes enable row level security;
create policy "family profiles visible to signed in family" on public.family_members for select to authenticated using(true);
create policy "own profile insert" on public.family_members for insert to authenticated with check(auth.uid()=id);
create policy "own profile update" on public.family_members for update to authenticated using(auth.uid()=id) with check(auth.uid()=id);
create policy "attempt status visible to family" on public.cup_attempts for select to authenticated using(true);
create policy "own attempt once" on public.cup_attempts for insert to authenticated with check(auth.uid()=user_id);
create policy "wishes visible to family" on public.wishes for select to authenticated using(true);
create policy "own wishes manage" on public.wishes for all to authenticated using(auth.uid()=owner_id) with check(auth.uid()=owner_id);
create policy "buyer gift notes only" on public.gift_notes for select to authenticated using(auth.uid()=buyer_id);
create policy "buyer gift notes insert" on public.gift_notes for insert to authenticated with check(auth.uid()=buyer_id and auth.uid()<>recipient_id);
create policy "buyer gift notes update" on public.gift_notes for update to authenticated using(auth.uid()=buyer_id) with check(auth.uid()=buyer_id and auth.uid()<>recipient_id);
create policy "buyer gift notes delete" on public.gift_notes for delete to authenticated using(auth.uid()=buyer_id);
